#pragma once

#ifndef KISAK_SP
#error This file is Single-Player only
#endif
#include <universal/q_parse.h>
#include "g_scr_main.h"

#include <bgame/bg_public.h>

#define MAX_VEHICLES 64

enum loading_t : __int32
{
	LOADING_DONE = 0x0,
	LOADING_LEVEL = 0x1,
	LOADING_SAVEGAME = 0x2,
};

struct trigger_info_t
{
	unsigned __int16 entnum;
	unsigned __int16 otherEntnum;
	int useCount;
	int otherUseCount;
};

struct level_locals_t
{
	gclient_s *clients;
	gentity_s *gentities;
	int gentitySize;
	int num_entities;
	gentity_s *firstFreeEnt;
	gentity_s *lastFreeEnt;
	sentient_s *sentients;
	actor_s *actors;
	scr_vehicle_s *vehicles;
	TurretInfo *turrets;
	int initializing;
	int clientIsSpawning;
	int maxclients;
	int framenum;
	int time;
	int previousTime;
	int snapTime;
	int newSession;
	int actorCorpseCount;
	SpawnVar spawnVar;
	int reloadDelayTime;
	int absoluteReloadDelayTime;
	EntHandle droppedWeaponCue[32];
	int changelevel;
	int bMissionSuccess;
	int bMissionFailed;
	int exitTime;
	int savepersist;
	char cinematic[64];
	float fFogOpaqueDist;
	float fFogOpaqueDistSqrd;
	unsigned int grenadeHintCount;
	int remapCount;
	int iSearchFrame;
	loading_t loading;
	int actorPredictDepth;
	int bDrawCompassFriendlies;
	int bPlayerIgnoreRadiusDamage;
	int bPlayerIgnoreRadiusDamageLatched;
	unsigned __int8 triggerIndex;
	int currentEntityThink;
	int currentIndex;
	bool checkAnimChange;
	int bRegisterItems;
	int framePos;
	bool demoplaying;
	int mpviewer;
	cached_tag_mat_t cachedTagMat;
	cached_tag_mat_t cachedEntTargetTagMat;
	unsigned __int16 soundAliasFirst;
	unsigned __int16 soundAliasLast;
	trigger_info_t pendingTriggerList[256];
	trigger_info_t currentTriggerList[256];
	int pendingTriggerListSize;
	int currentTriggerListSize;
	unsigned __int8 entTriggerIndex[MAX_GENTITIES];
	unsigned __int8 specialIndex[MAX_GENTITIES];
	actor_prone_info_s cgData_actorProneInfo[48];
	unsigned __int8 cgData_actorOnCompass[32];
	unsigned __int8 cgData_actorTeam[32];
	unsigned __int16 modelMap[512];
	float priorityNodeBias;
	//void *openScriptIOFileHandles[1];
	int openScriptIOFileHandles[1];
	unsigned char *openScriptIOFileBuffers[1];
	com_parse_mark_t currentScriptIOLineMark[1];
	int scriptPrintChannel;
	float compassMapUpperLeft[2];
	float compassMapWorldSize[2];
	float compassNorth[2];
	float mapSunColor[3];
	float mapSunDirection[3];
};

extern const dvar_t *turretPlayerAvoidScale;
extern const dvar_t *ai_debugFindPathDirect;
extern const dvar_t *ai_playerNearRange;
extern const dvar_t *g_entinfo_scale;
extern const dvar_t *g_entinfo_AItext;
extern const dvar_t *vehHelicopterTiltFromControllerAxes;
extern const dvar_t *player_damageMultiplier;
extern const dvar_t *ai_playerADSTargetTime;
extern const dvar_t *g_gravity;
extern const dvar_t *vehHelicopterTiltFromFwdAndYaw;
extern const dvar_t *ai_debugPlayerLOS;
extern const dvar_t *ai_eventDistGunShot;
extern const dvar_t *ai_showClaimedNode;
extern const dvar_t *vehHelicopterJitterJerkyness;
extern const dvar_t *g_playerTrailTime;
extern const dvar_t *vehHelicopterTiltSpeed;
extern const dvar_t *radius_damage_debug;
extern const dvar_t *ai_showDodge;
extern const dvar_t *ai_debugFindPathWidth;
extern const dvar_t *ai_showVisDataDist;
extern const dvar_t *ai_coverScore_coverType;
extern const dvar_t *ai_showBadPlaces;
extern const dvar_t *ai_playerNearAccuracy;
extern const dvar_t *ai_playerLOSRange;
extern const dvar_t *g_dumpAnims;
extern const dvar_t *ai_eventDistPain;
extern const dvar_t *vehHelicopterInvertUpDown;
extern const dvar_t *ai_showSuppression;
extern const dvar_t *vehHelicopterMaxYawAccel;
extern const dvar_t *g_dumpAnimsCommands;
extern const dvar_t *vehHelicopterLookaheadTime;
extern const dvar_t *ai_eventDistSilencedShot;
extern const dvar_t *g_dumpAIEvents;
extern const dvar_t *ai_noDodge;
extern const dvar_t *ai_showVolume;
extern const dvar_t *g_vehHudTargetScreenEdgeClampBufferBottom;
extern const dvar_t *g_friendlyfireDist;
extern const dvar_t *g_dumpAIEventListeners;
extern const dvar_t *g_ai;
extern const dvar_t *vehHelicopterMaxSpeedVertical;
extern const dvar_t *ai_eventDistFootstep;
extern const dvar_t *g_enteqEnable;
extern const dvar_t *ai_friendlySuppression;
extern const dvar_t *g_vehicleDrawPath;
extern const dvar_t *ai_debugFindPathLock;
extern const dvar_t *vehHelicopterTiltFromDeceleration;
extern const dvar_t *ai_showNodes;
extern const dvar_t *ai_coverScore_playerLos;
extern const dvar_t *g_debugBullets;
extern const dvar_t *g_drawEntBBoxes;
extern const dvar_t *vehHelicopterRightStickDeadzone;
extern const dvar_t *player_deathInvulnerableToMelee;
extern const dvar_t *ai_debugGrenadeHintArc;
extern const dvar_t *ai_debugMayMove;
extern const dvar_t *g_knockback;
extern const dvar_t *ai_badPathSpam;
extern const dvar_t *g_vehHudTargetScreenEdgeClampBufferLeft;
extern const dvar_t *ai_ShowCanshootChecks;
extern const dvar_t *player_throwbackInnerRadius;
extern const dvar_t *ai_showPaths;
extern const dvar_t *ai_useBetterLookahead; // USEBETTERLOOKAHEAD
extern const dvar_t *ai_accuracyDistScale;
extern const dvar_t *g_vehHudTargetSize;
extern const dvar_t *ai_debugMeleeAttackSpots;
extern const dvar_t *ai_threatUpdateInterval;
extern const dvar_t *player_deathInvulnerableToProjectile;
extern const dvar_t *ai_friendlySuppressionDist;
extern const dvar_t *g_earthquakeEnable;
extern const dvar_t *ai_eventDistExplosion;
extern const dvar_t *vehHelicopterSoftCollisions;
extern const dvar_t *ai_coverScore_nodeAngle;
extern const dvar_t *g_entinfo;
extern const dvar_t *vehHelicopterYawOnLeftStick;
extern const dvar_t *melee_debug;
extern const dvar_t *vehHelicopterDecelerationFwd;
extern const dvar_t *ai_debugThreatSelection;
extern const dvar_t *ai_debugEntIndex;
extern const dvar_t *ai_corpseCount;
extern const dvar_t *g_player_maxhealth;
extern const dvar_t *vehHelicopterMaxAccelVertical;
extern const dvar_t *g_vehicleDebug;
extern const dvar_t *g_entinfo_type;
extern const dvar_t *ai_showPotentialThreatDir;
extern const dvar_t *ai_showFriendlyChains;
extern const dvar_t *g_weaponAmmoPools;
extern const dvar_t *ai_eventDistDeath;
extern const dvar_t *g_enteqDist;
extern const dvar_t *g_fogColorReadOnly;
extern const dvar_t *g_deathDelay;
extern const dvar_t *ai_eventDistProjImpact;
extern const dvar_t *ai_debugAccuracy;
extern const dvar_t *ai_debugGrenadeFailSafe;
extern const dvar_t *g_vehHudTargetScreenEdgeClampBufferRight;
extern const dvar_t *g_recordScriptPlace;
extern const dvar_t *vehHelicopterMaxPitch;
extern const dvar_t *ai_eventDistFootstepLite;
extern const dvar_t *ai_foliageIngoreDist;
extern const dvar_t *g_listEntity;
extern const dvar_t *ai_eventDistProjPing;
extern const dvar_t *vehHelicopterTiltFromAcceleration;
extern const dvar_t *g_cheats;
extern const dvar_t *g_fogHalfDistReadOnly;
extern const dvar_t *chaplinCheat;
extern const dvar_t *g_vehicleTexScrollScale;
extern const dvar_t *g_spawnai;
extern const dvar_t *ai_playerADS_LOSRange;
extern const dvar_t *g_minGrenadeDamageSpeed;
extern const dvar_t *vehHelicopterStrafeDeadzone;
extern const dvar_t *vehHelicopterHoverSpeedThreshold;
extern const dvar_t *ai_disableSpawn;
extern const dvar_t *ai_showVisData;
extern const dvar_t *g_vehHudTargetScreenEdgeClampBufferTop;
extern const dvar_t *vehHelicopterMaxYawRate;
extern const dvar_t *ai_debugClaimedNodes;
extern const dvar_t *vehHelicopterMaxAccel;
extern const dvar_t *g_useholdtime;
extern const dvar_t *vehHelicopterYawAltitudeControls;
extern const dvar_t *g_speed;
extern const dvar_t *g_friendlyNameDist;
extern const dvar_t *player_meleeDamageMultiplier;
extern const dvar_t *ai_moveOrientMode;
extern const dvar_t *ai_coverScore_engagement;
extern const dvar_t *ai_eventDistGrenadePing;
extern const dvar_t *ai_playerLOSHalfWidth;
extern const dvar_t *vehHelicopterMaxRoll;
extern const dvar_t *g_drawGrenadeHints;
extern const dvar_t *bullet_penetrationEnabled;
extern const dvar_t *vehHelicopterScaleMovement;
extern const dvar_t *g_entinfo_maxdist;
extern const dvar_t *ai_debugAnimDeltas;
extern const dvar_t *ai_eventDistBadPlace;
extern const dvar_t *ai_showNearestNode;
extern const dvar_t *player_deathInvulnerableTime;
extern const dvar_t *g_reloading;
extern const dvar_t *vehHelicopterMaxSpeed;
extern const dvar_t *g_NoScriptSpam;
extern const dvar_t *g_enteqDelay;
extern const dvar_t *ai_eventDistNewEnemy;
extern const dvar_t *ai_coverScore_visibility;
extern const dvar_t *g_fogStartDistReadOnly;
extern const dvar_t *ai_coverScore_targetDir;
extern const dvar_t *player_maxGrenadeCatchHeight;
extern const dvar_t *ai_eventDistBullet;
extern const dvar_t *vehHelicopterTiltFromVelocity;
extern const dvar_t *g_debugLocDamage;
extern const dvar_t *ai_friendlyFireBlockDuration;
extern const dvar_t *ai_debugFindPath;
extern const dvar_t *g_changelevel_time;
extern const dvar_t *ai_coverScore_distance;
extern const dvar_t *player_throwbackOuterRadius;
extern const dvar_t *ai_debugCoverEntityNum;
extern const dvar_t *vehHelicopterTiltMomentum;
extern const dvar_t *ai_playerFarAccuracy;
extern const dvar_t *ai_debugCoverSelection;
extern const dvar_t *vehHelicopterHeadSwayDontSwayTheTurret;
extern const dvar_t *ai_playerFarRange;
extern const dvar_t *ai_showRegion;
extern const dvar_t *ai_coverScore_priority;
extern const dvar_t *ai_pathMomentum;
extern const dvar_t *ai_showNodesDist;
extern const dvar_t *g_debugDamage;
extern const dvar_t *vehHelicopterTiltFromFwdAndYaw_VelAtMaxTilt;
extern const dvar_t *ai_pathNegotiationOverlapCost;
extern const dvar_t *vehHelicopterDecelerationSide;
extern const dvar_t *pickupPrints;
extern const dvar_t *ai_playerLOSMinTime;
extern const dvar_t *player_radiusDamageMultiplier;

extern struct entityHandler_t entityHandlers[27];
extern gentity_s g_entities[MAX_GENTITIES];
extern sentient_s g_sentients[33];
extern char g_nextMap[64];
extern level_locals_t level;
extern gclient_s g_clients[1];
extern actor_s g_actors[32];

extern scr_vehicle_s s_vehicles[64];