#pragma once
#include <cstdint>

#ifdef KISAK_MP
struct scr_const_t // sizeof=0x174
{                                       // ...
    uint16_t _;                 // ...
    uint16_t active;            // ...
    uint16_t aim_bone;          // ...
    uint16_t aim_highest_bone;  // ...
    uint16_t aim_vis_bone;      // ...
    uint16_t all;               // ...
    uint16_t allies;            // ...
    uint16_t axis;              // ...
    uint16_t bad_path;          // ...
    uint16_t begin_firing;      // ...
    uint16_t cancel_location;   // ...
    uint16_t confirm_location;  // ...
    uint16_t crouch;            // ...
    uint16_t current;           // ...
    uint16_t damage;            // ...
    uint16_t dead;              // ...
    uint16_t death;             // ...
    uint16_t detonate;          // ...
    uint16_t direct;            // ...
    uint16_t dlight;            // ...
    uint16_t done;              // ...
    uint16_t empty;             // ...
    uint16_t end_firing;        // ...
    uint16_t entity;            // ...
    uint16_t explode;           // ...
    uint16_t failed;            // ...
    uint16_t free;              // ...
    uint16_t fraction;          // ...
    uint16_t goal;              // ...
    uint16_t goal_changed;      // ...
    uint16_t goal_yaw;          // ...
    uint16_t grenade;           // ...
    uint16_t grenadedanger;     // ...
    uint16_t grenade_fire;      // ...
    uint16_t grenade_pullback;  // ...
    uint16_t info_notnull;      // ...
    uint16_t invisible;         // ...
    uint16_t key1;              // ...
    uint16_t key2;              // ...
    uint16_t killanimscript;    // ...
    uint16_t left;              // ...
    uint16_t light;             // ...
    uint16_t movedone;          // ...
    uint16_t noclass;           // ...
    uint16_t none;              // ...
    uint16_t normal;            // ...
    uint16_t player;            // ...
    uint16_t position;          // ...
    uint16_t projectile_impact; // ...
    uint16_t prone;             // ...
    uint16_t right;             // ...
    uint16_t reload;            // ...
    uint16_t reload_start;      // ...
    uint16_t rocket;            // ...
    uint16_t rotatedone;        // ...
    uint16_t script_brushmodel; // ...
    uint16_t script_model;      // ...
    uint16_t script_origin;     // ...
    uint16_t snd_enveffectsprio_level; // ...
    uint16_t snd_enveffectsprio_shellshock; // ...
    uint16_t snd_channelvolprio_holdbreath; // ...
    uint16_t snd_channelvolprio_pain; // ...
    uint16_t snd_channelvolprio_shellshock; // ...
    uint16_t stand;             // ...
    uint16_t suppression;       // ...
    uint16_t suppression_end;   // ...
    uint16_t surfacetype;       // ...
    uint16_t tag_aim;           // ...
    uint16_t tag_aim_animated;  // ...
    uint16_t tag_brass;         // ...
    uint16_t tag_butt;          // ...
    uint16_t tag_clip;          // ...
    uint16_t tag_flash;         // ...
    uint16_t tag_flash_11;      // ...
    uint16_t tag_flash_2;       // ...
    uint16_t tag_flash_22;      // ...
    uint16_t tag_flash_3;       // ...
    uint16_t tag_fx;            // ...
    uint16_t tag_inhand;        // ...
    uint16_t tag_knife_attach;  // ...
    uint16_t tag_knife_fx;      // ...
    uint16_t tag_laser;         // ...
    uint16_t tag_origin;        // ...
    uint16_t tag_weapon;        // ...
    uint16_t tag_player;        // ...
    uint16_t tag_camera;        // ...
    uint16_t tag_weapon_right;  // ...
    uint16_t tag_gasmask;       // ...
    uint16_t tag_gasmask2;      // ...
    uint16_t tag_sync;          // ...
    uint16_t target_script_trigger; // ...
    uint16_t tempEntity;        // ...
    uint16_t top;               // ...
    uint16_t touch;             // ...
    uint16_t trigger;           // ...
    uint16_t trigger_use;       // ...
    uint16_t trigger_use_touch; // ...
    uint16_t trigger_damage;    // ...
    uint16_t trigger_lookat;    // ...
    uint16_t truck_cam;         // ...
    uint16_t weapon_change;     // ...
    uint16_t weapon_fired;      // ...
    uint16_t worldspawn;        // ...
    uint16_t flashbang;         // ...
    uint16_t flash;             // ...
    uint16_t smoke;             // ...
    uint16_t night_vision_on;   // ...
    uint16_t night_vision_off;  // ...
    uint16_t mod_unknown;       // ...
    uint16_t mod_pistol_bullet; // ...
    uint16_t mod_rifle_bullet;  // ...
    uint16_t mod_grenade;       // ...
    uint16_t mod_grenade_splash; // ...
    uint16_t mod_projectile;    // ...
    uint16_t mod_projectile_splash; // ...
    uint16_t mod_melee;         // ...
    uint16_t mod_head_shot;     // ...
    uint16_t mod_crush;         // ...
    uint16_t mod_telefrag;      // ...
    uint16_t mod_falling;       // ...
    uint16_t mod_suicide;       // ...
    uint16_t mod_trigger_hurt;  // ...
    uint16_t mod_explosive;     // ...
    uint16_t mod_impact;        // ...
    uint16_t script_vehicle;    // ...
    uint16_t script_vehicle_collision; // ...
    uint16_t script_vehicle_collmap; // ...
    uint16_t script_vehicle_corpse; // ...
    uint16_t turret_fire;       // ...
    uint16_t turret_on_target;  // ...
    uint16_t turret_not_on_target; // ...
    uint16_t turret_on_vistarget; // ...
    uint16_t turret_no_vis;     // ...
    uint16_t turret_rotate_stopped; // ...
    uint16_t turret_deactivate; // ...
    uint16_t turretstatechange; // ...
    uint16_t turretownerchange; // ...
    uint16_t reached_end_node;  // ...
    uint16_t reached_wait_node; // ...
    uint16_t reached_wait_speed; // ...
    uint16_t near_goal;         // ...
    uint16_t veh_collision;     // ...
    uint16_t veh_predictedcollision; // ...
    uint16_t auto_change;       // ...
    uint16_t back_low;          // ...
    uint16_t back_mid;          // ...
    uint16_t back_up;           // ...
    uint16_t begin;             // ...
    uint16_t call_vote;         // ...
    uint16_t freelook;          // ...
    uint16_t head;              // ...
    uint16_t intermission;      // ...
    uint16_t j_head;            // ...
    uint16_t manual_change;     // ...
    uint16_t menuresponse;      // ...
    uint16_t neck;              // ...
    uint16_t pelvis;            // ...
    uint16_t pistol;            // ...
    uint16_t plane_waypoint;    // ...
    uint16_t playing;           // ...
    uint16_t spectator;         // ...
    uint16_t vote;              // ...
    uint16_t sprint_begin;      // ...
    uint16_t sprint_end;        // ...
    uint16_t tag_driver;        // ...
    uint16_t tag_passenger;     // ...
    uint16_t tag_gunner;        // ...
    uint16_t tag_wheel_front_left; // ...
    uint16_t tag_wheel_front_right; // ...
    uint16_t tag_wheel_back_left; // ...
    uint16_t tag_wheel_back_right; // ...
    uint16_t tag_wheel_middle_left; // ...
    uint16_t tag_wheel_middle_right; // ...
    uint16_t tag_detach;        // ...
    uint16_t tag_popout;        // ...
    uint16_t tag_body;          // ...
    uint16_t tag_turret;        // ...
    uint16_t tag_turret_base;   // ...
    uint16_t tag_barrel;        // ...
    uint16_t tag_engine_left;   // ...
    uint16_t tag_engine_right;  // ...
    uint16_t front_left;        // ...
    uint16_t front_right;       // ...
    uint16_t back_left;         // ...
    uint16_t back_right;        // ...
    uint16_t tag_gunner_pov;    // ...
};
static_assert(sizeof(scr_const_t) == 0x174);

#elif KISAK_SP
struct scr_const_t
{
    uint16_t _;
    uint16_t active;
    uint16_t aim_bone;
    uint16_t aim_highest_bone;
    uint16_t aim_vis_bone;
    uint16_t all;
    uint16_t allies;
    uint16_t axis;
    uint16_t bad_path;
    uint16_t begin_firing;
    uint16_t cancel_location;
    uint16_t confirm_location;
    uint16_t crouch;
    uint16_t current;
    uint16_t damage;
    uint16_t dead;
    uint16_t death;
    uint16_t detonate;
    uint16_t direct;
    uint16_t dlight;
    uint16_t done;
    uint16_t empty;
    uint16_t end_firing;
    uint16_t entity;
    uint16_t explode;
    uint16_t failed;
    uint16_t free;
    uint16_t fraction;
    uint16_t goal;
    uint16_t goal_changed;
    uint16_t goal_yaw;
    uint16_t grenade;
    uint16_t grenadedanger;
    uint16_t grenade_fire;
    uint16_t grenade_pullback;
    uint16_t info_notnull;
    uint16_t invisible;
    uint16_t key1;
    uint16_t key2;
    uint16_t killanimscript;
    uint16_t left;
    uint16_t light;
    uint16_t movedone;
    uint16_t noclass;
    uint16_t none;
    uint16_t normal;
    uint16_t player;
    uint16_t position;
    uint16_t projectile_impact;
    uint16_t prone;
    uint16_t right;
    uint16_t reload;
    uint16_t reload_start;
    uint16_t rocket;
    uint16_t rotatedone;
    uint16_t script_brushmodel;
    uint16_t script_model;
    uint16_t script_origin;
    uint16_t snd_enveffectsprio_level;
    uint16_t snd_enveffectsprio_shellshock;
    uint16_t snd_channelvolprio_holdbreath;
    uint16_t snd_channelvolprio_pain;
    uint16_t snd_channelvolprio_shellshock;
    uint16_t stand;
    uint16_t suppression;
    uint16_t suppression_end;
    uint16_t surfacetype;
    uint16_t tag_aim;
    uint16_t tag_aim_animated;
    uint16_t tag_brass;
    uint16_t tag_butt;
    uint16_t tag_clip;
    uint16_t tag_flash;
    uint16_t tag_flash_11;
    uint16_t tag_flash_2;
    uint16_t tag_flash_22;
    uint16_t tag_flash_3;
    uint16_t tag_fx;
    uint16_t tag_inhand;
    uint16_t tag_knife_attach;
    uint16_t tag_knife_fx;
    uint16_t tag_laser;
    uint16_t tag_origin;
    uint16_t tag_weapon;
    uint16_t tag_player;
    uint16_t tag_camera;
    uint16_t tag_weapon_right;
    uint16_t tag_gasmask;
    uint16_t tag_gasmask2;
    uint16_t tag_sync;
    uint16_t target_script_trigger;
    uint16_t tempEntity;
    uint16_t top;
    uint16_t touch;
    uint16_t trigger;
    uint16_t trigger_use;
    uint16_t trigger_use_touch;
    uint16_t trigger_damage;
    uint16_t trigger_lookat;
    uint16_t truck_cam;
    uint16_t weapon_change;
    uint16_t weapon_fired;
    uint16_t worldspawn;
    uint16_t flashbang;
    uint16_t flash;
    uint16_t smoke;
    uint16_t night_vision_on;
    uint16_t night_vision_off;
    uint16_t mod_unknown;
    uint16_t mod_pistol_bullet;
    uint16_t mod_rifle_bullet;
    uint16_t mod_grenade;
    uint16_t mod_grenade_splash;
    uint16_t mod_projectile;
    uint16_t mod_projectile_splash;
    uint16_t mod_melee;
    uint16_t mod_head_shot;
    uint16_t mod_crush;
    uint16_t mod_telefrag;
    uint16_t mod_falling;
    uint16_t mod_suicide;
    uint16_t mod_trigger_hurt;
    uint16_t mod_explosive;
    uint16_t mod_impact;
    uint16_t script_vehicle;
    uint16_t script_vehicle_collision;
    uint16_t script_vehicle_collmap;
    uint16_t script_vehicle_corpse;
    uint16_t turret_fire;
    uint16_t turret_on_target;
    uint16_t turret_not_on_target;
    uint16_t turret_on_vistarget;
    uint16_t turret_no_vis;
    uint16_t turret_rotate_stopped;
    uint16_t turret_deactivate;
    uint16_t turretstatechange;
    uint16_t turretownerchange;
    uint16_t reached_end_node;
    uint16_t reached_wait_node;
    uint16_t reached_wait_speed;
    uint16_t near_goal;
    uint16_t veh_collision;
    uint16_t veh_predictedcollision;
    uint16_t _custom;
    uint16_t always;
    uint16_t auto_ai;
    uint16_t auto_nonai;
    uint16_t angle_deltas;
    uint16_t back_left;
    uint16_t back_right;
    uint16_t begin_custom_anim;
    uint16_t bullethit;
    uint16_t bulletwhizby;
    uint16_t count;
    uint16_t corner_approach;
    uint16_t damage_notdone;
    uint16_t deathplant;
    uint16_t enemy;
    uint16_t enemy_visible;
    uint16_t face_angle;
    uint16_t face_current;
    uint16_t face_default;
    uint16_t face_direction;
    uint16_t face_enemy;
    uint16_t face_enemy_or_motion;
    uint16_t face_goal;
    uint16_t face_motion;
    uint16_t face_point;
    uint16_t front_left;
    uint16_t front_right;
    uint16_t gravity;
    uint16_t grenade_return_hand_tag;
    uint16_t groundEntChanged;
    uint16_t gunshot;
    uint16_t high_priority;
    uint16_t info_player_deathmatch;
    uint16_t infinite_energy;
    uint16_t low_priority;
    uint16_t obstacle;
    uint16_t manual;
    uint16_t manual_ai;
    uint16_t max_time;
    uint16_t menuresponse;
    uint16_t middle_left;
    uint16_t middle_right;
    uint16_t min_energy;
    uint16_t min_time;
    uint16_t movemode;
    uint16_t neutral;
    uint16_t never;
    uint16_t noclip;
    uint16_t node_out_of_range;
    uint16_t node_relinquished;
    uint16_t node_taken;
    uint16_t node_not_safe;
    uint16_t nogravity;
    uint16_t nophysics;
    uint16_t pain;
	uint16_t path_changed;
    uint16_t pickup;
    uint16_t receiver;
    uint16_t run;
    uint16_t runto_arrived;
    uint16_t silenced_shot;
    uint16_t sound_blend;
    uint16_t spawned;
    uint16_t start_move;
    uint16_t stop;
    uint16_t stop_soon;
    uint16_t tag_eye;
    uint16_t tag_wheel_front_left;
    uint16_t tag_wheel_front_right;
    uint16_t tag_wheel_back_left;
    uint16_t tag_wheel_back_right;
    uint16_t tag_wheel_middle_left;
    uint16_t tag_wheel_middle_right;
    uint16_t tag_detach;
    uint16_t tag_popout;
    uint16_t tag_body;
    uint16_t tag_turret;
    uint16_t tag_turret_base;
    uint16_t tag_barrel;
    uint16_t tag_weapon_left;
    uint16_t walk;
    uint16_t world;
    uint16_t zonly_physics;
    uint16_t human;
    uint16_t dog;
};
#endif
void __cdecl GScr_LoadConsts(void);


extern scr_const_t scr_const;
