#pragma once

struct GenericAabbTree // sizeof=0x10
{
    int firstItem;
    int itemCount;
    int firstChild;
    int childCount;
};
struct GenericAabbTreeOptions // sizeof=0x28
{                                       // ...
    void *items;                        // ...
    int itemCount;                      // ...
    int itemSize;                       // ...
    int maintainValidBounds;            // ...
    float (*mins)[3];                   // ...
    float (*maxs)[3];                   // ...
    GenericAabbTree *treeNodePool;      // ...
    int treeNodeLimit;                  // ...
    int minItemsPerLeaf;                // ...
    int maxItemsPerLeaf;                // ...
};

int __cdecl BuildAabbTree(const GenericAabbTreeOptions *options);
