#pragma once
#include "q_shared.h"

#define PROF_NAME0 "",
#define PROF_NAME1 "Probe1",
#define PROF_NAME2 "Probe2",
#define PROF_NAME3 "Probe3",
#define PROF_NAME4 "Probe4",
#define PROF_NAME5 "Probe5",
#define PROF_NAME6 "GProbe1",
#define PROF_NAME7 "GProbe2",
#define PROF_NAME8 "GProbe3",
#define PROF_NAME9 "GProbe4",
#define PROF_NAME10 "GProbe5",
#define PROF_NAME11 "CG_ProcessSnapshots",
#define PROF_NAME12 "CG_UpdateEntInfo",
#define PROF_NAME13 "CG_DrawActiveFrame",
#define PROF_NAME14 "R_RenderScene",
#define PROF_NAME15 "R_IssueRenderCommands",
#define PROF_NAME16 "CL_Frame",
#define PROF_NAME17 "CL_RunOncePerFrame",
#define PROF_NAME18 "SCR_UpdateFrame",
#define PROF_NAME19 "CL_BeginFrame",
#define PROF_NAME20 "CL_DrawFrame",
#define PROF_NAME21 "CL_EndFrame",
#define PROF_NAME22 "CG_DAF_UpdateEffects",
#define PROF_NAME23 "CG_DAF_AddLocalEntities",
#define PROF_NAME24 "CG_DAF_SmoothFrame",
#define PROF_NAME25 "CG_DrawActive",
#define PROF_NAME26 "CG_Pmove",
#define PROF_NAME27 "G_Pmove",
#define PROF_NAME28 "CbufExecute",
#define PROF_NAME29 "Com_ClientPacketEvent",
#define PROF_NAME30 "Com_ServerPacketEvent",
#define PROF_NAME31 "SV_BuildAndSendClientSnapshot",
#define PROF_NAME32 "NetworkRead",
#define PROF_NAME33 "NetworkWrite",
#define PROF_NAME34 "SCR_UpdateScreen",
#define PROF_NAME35 "CM_TerrainTrace",
#define PROF_NAME36 "CM_CurveTrace",
#define PROF_NAME37 "SV_Trace",
#define PROF_NAME38 "SV_TracePassed",
#define PROF_NAME39 "CM_Trace",
#define PROF_NAME40 "CM_SightTrace",
#define PROF_NAME41 "CM_AreaEntities",
#define PROF_NAME42 "CM_LinkEntity",
#define PROF_NAME43 "CM_PointSightTraceToEntities",
#define PROF_NAME44 "CM_ClipSightTraceToEntities",
#define PROF_NAME45 "CM_TraceBrush",
#define PROF_NAME46 "CM_TraceTerrain",
#define PROF_NAME47 "CM_SightBrush",
#define PROF_NAME48 "CM_SightTerrain",
#define PROF_NAME49 "CG_UnlinkEntity",
#define PROF_NAME50 "CG_LinkEntity",
#define PROF_NAME51 "CG_LocationalTrace",
#define PROF_NAME52 "CG_TraceCapsule",
#define PROF_NAME53 "CG_Trace",
#define PROF_NAME54 "CG_ClipMoveToEntities",
#define PROF_NAME55 "CG_ClipMoveToEntity",
#define PROF_NAME56 "CG_PointTraceToEntities",
#define PROF_NAME57 "CG_PointTraceToEntity",
#define PROF_NAME58 "AimTarget_ProcessEntity",
#define PROF_NAME59 "AimTarget_IsTargetValid",
#define PROF_NAME60 "AimTarget_IsTargetVisible",
#define PROF_NAME61 "AimTarget_CreateTarget",
#define PROF_NAME62 "AimAssist_UpdateGamePadInput",
#define PROF_NAME63 "AimAssist_UpdateMouseInput",
#define PROF_NAME64 "AimAssist_UpdateScreenTargets",
#define PROF_NAME65 "R_EmitDrawSurfList",
#define PROF_NAME66 "R_DrawSunShadowPartition",
#define PROF_NAME67 "R_BoundScene",
#define PROF_NAME68 "R_BoundAndPartitionScene",
#define PROF_NAME69 "R_AddEntitySurfaces",
#define PROF_NAME70 "R_DoesDrawSurfListInfoNeedFloatz",
#define PROF_NAME71 "R_AddWorldSurfacesDpvs",
#define PROF_NAME72 "R_AddShadowSurfacesDpvs",
#define PROF_NAME73 "GenerateSunShadow",
#define PROF_NAME74 "EmitSpotShadow",
#define PROF_NAME75 "EmitSunShadow",
#define PROF_NAME76 "R_SunShadowMaps",
#define PROF_NAME77 "R_DepthPrepass",
#define PROF_NAME78 "R_StreamUpdate",
#define PROF_NAME79 "R_StreamUpdateStatic",
#define PROF_NAME80 "R_StreamUpdateDynamicModels",
#define PROF_NAME81 "RB_StreamExecuteQueuedCommands",
#define PROF_NAME82 "R_StreamAlloc_Alloc",
#define PROF_NAME83 "R_StreamAlloc_RunOptimizationTask",
#define PROF_NAME84 "R_ConvexHull",
#define PROF_NAME85 "R_GetStaticLights",
#define PROF_NAME86 "R_PickFinalLights",
#define PROF_NAME87 "R_LightCacheTrace",
#define PROF_NAME88 "R_SortDrawSurfs",
#define PROF_NAME89 "R_SkinXModel",
#define PROF_NAME90 "RB_DrawTechnique",
#define PROF_NAME91 "RB_SetSampler",
#define PROF_NAME92 "RB_SetVertexShaderConstant",
#define PROF_NAME93 "RB_SetPixelShaderConstant",
#define PROF_NAME94 "RB_SetVertexDeclaration",
#define PROF_NAME95 "RB_SetVertexShader",
#define PROF_NAME96 "RB_SetPixelShader",
#define PROF_NAME97 "RB_SetParticleCloudConstants",
#define PROF_NAME98 "R_DrawSurfs",
#define PROF_NAME99 "rb_surfaceTable",
#define PROF_NAME100 "TessCodeMesh",
#define PROF_NAME101 "TessCloud",
#define PROF_NAME102 "TessXModSkin",
#define PROF_NAME103 "TessXModSkinCach",
#define PROF_NAME104 "TessXModSkinUncach",
#define PROF_NAME105 "TessXModRigid",
#define PROF_NAME106 "TessStaticModel",
#define PROF_NAME107 "TessStaticModelCached",
#define PROF_NAME108 "TessTriangles",
#define PROF_NAME109 "TessBModel",
#define PROF_NAME110 "TessSharedShadowCaster",
#define PROF_NAME111 "SkinXSurfaceWeight",
#define PROF_NAME112 "EndSurface",
#define PROF_NAME113 "EndSurface_Optimized",
#define PROF_NAME114 "EndSurface_Standard",
#define PROF_NAME115 "RB_ProcessPostEffects",
#define PROF_NAME116 "RB_ApplyPostEffects",
#define PROF_NAME117 "RB_UpdateAverageSceneBrightnessImage",
#define PROF_NAME118 "RB_GlowEffect",
#define PROF_NAME119 "RB_UploadWaterTexture",
#define PROF_NAME120 "RB_DrawSunQuerySprite",
#define PROF_NAME121 "R_SyncGpu",
#define PROF_NAME122 "FrequenciesAtTime",
#define PROF_NAME123 "AmplitudesFromFrequencies",
#define PROF_NAME124 "PixelsFromAmplitudes",
#define PROF_NAME125 "ProcessImage",
#define PROF_NAME126 "UploadImage",
#define PROF_NAME127 "GenerateMipMaps",
#define PROF_NAME128 "Present",
#define PROF_NAME129 "DrawIndexedPrimitive",
#define PROF_NAME130 "DrawIndexedPrimitiveUP",
#define PROF_NAME131 "SetVertexShaderConstant",
#define PROF_NAME132 "SetPixelShaderConstant",
#define PROF_NAME133 "WaitRenderer",
#define PROF_NAME134 "WaitFX",
#define PROF_NAME135 "WaitSpotLightFX",
#define PROF_NAME136 "WaitDepFX",
#define PROF_NAME137 "WaitRenderSwap",
#define PROF_NAME138 "WaitUpdateEvent",
#define PROF_NAME139 "WaitOtherThread",
#define PROF_NAME140 "RB_DrawProfileCmd",
#define PROF_NAME141 "RB_Draw3D",
#define PROF_NAME142 "R_SetupPass",
#define PROF_NAME143 "WaitWater",
#define PROF_NAME144 "R_Cinematic_UpdateFrame",
#define PROF_NAME145 "R_Cinematic_Advance",
#define PROF_NAME146 "BinkDoFrame",
#define PROF_NAME147 "BinkNextFrame",
#define PROF_NAME148 "BinkWait",
#define PROF_NAME149 "RB_LimitQueuedFrames",
#define PROF_NAME150 "SC_FindCasters",
#define PROF_NAME151 "SC_AddReceivers",
#define PROF_NAME152 "SC_DrawCaster",
#define PROF_NAME153 "SC_FindReceivers",
#define PROF_NAME154 "SC_DrawReceivers",
#define PROF_NAME155 "SC_SkinXModel",
#define PROF_NAME156 "RB_SetIndexData",
#define PROF_NAME157 "LockIndexBufferDiscard",
#define PROF_NAME158 "LockIndexBufferNoOverwrite",
#define PROF_NAME159 "LockSkinnedCache",
#define PROF_NAME160 "UnlockSkinnedCache",
#define PROF_NAME161 "RB_SetVertexData",
#define PROF_NAME162 "LockIndexBuffer",
#define PROF_NAME163 "LockVertexBuffer",
#define PROF_NAME164 "LockSModelBuffer",
#define PROF_NAME165 "BindTexture",
#define PROF_NAME166 "R_memcpy",
#define PROF_NAME167 "RB_memcpy",
#define PROF_NAME168 "RB_memcpy_it",
#define PROF_NAME169 "RB_memcpy_vt",
#define PROF_NAME170 "RB_memcpy_ib",
#define PROF_NAME171 "RB_memcpy_vb",
#define PROF_NAME172 "RendererSleep",
#define PROF_NAME173 "FrontEndSleep",
#define PROF_NAME174 "WorkerThread",
#define PROF_NAME175 "WaitForWorkerCmd",
#define PROF_NAME176 "WaitWorkerCmds",
#define PROF_NAME177 "ProcessWorkerCmds",
#define PROF_NAME178 "PixelShaderSurfs",
#define PROF_NAME179 "PixelShader",
#define PROF_NAME180 "StaticCull",
#define PROF_NAME181 "SceneEntCull",
#define PROF_NAME182 "DynModelCull",
#define PROF_NAME183 "DynBrushCull",
#define PROF_NAME184 "R_DrawStaticModelCmd",
#define PROF_NAME185 "R_DrawXModelCmd",
#define PROF_NAME186 "R_DrawTrianglesCmd",
#define PROF_NAME187 "SaveWriteThread",
#define PROF_NAME188 "R_VisitPortals",
#define PROF_NAME189 "ExecuteRenderCmds",
#define PROF_NAME190 "RB_memcpy_smc",
#define PROF_NAME191 "RB_memcpy_tris",
#define PROF_NAME192 "RB_memcpy_shadow",
#define PROF_NAME193 "FX_Update",
#define PROF_NAME194 "FX_UpdateOrigin",
#define PROF_NAME195 "FX_EndUpdate",
#define PROF_NAME196 "FX_GenerateVerts",
#define PROF_NAME197 "FX_GenElemVerts",
#define PROF_NAME198 "FX_EvalVisState",
#define PROF_NAME199 "FX_Sort",
#define PROF_NAME200 "FX_Draw",
#define PROF_NAME201 "FX_DrawElems",
#define PROF_NAME202 "FX_DrawSortedElems",
#define PROF_NAME203 "FX_Trace",
#define PROF_NAME204 "FX_CreateImpactMark",
#define PROF_NAME205 "FX_ImpactMark_World",
#define PROF_NAME206 "FX_ImpactMark_Models",
#define PROF_NAME207 "FX_ImpactMark_Generate_AddEntityModels",
#define PROF_NAME208 "FX_FreeLruMark",
#define PROF_NAME209 "FX_GenMarkVertsStaticModel",
#define PROF_NAME210 "FX_GenMarkVertsEnt",
#define PROF_NAME211 "FX_GenMarkVertsWorld",
#define PROF_NAME212 "FX_GetVisibility",
#define PROF_NAME213 "FX_StopEffect",
#define PROF_NAME214 "SV_FX_GetVisibility",
#define PROF_NAME215 "R_BoxStaticModels",
#define PROF_NAME216 "R_MarkFragments_SceneDObjs",
#define PROF_NAME217 "R_MarkUtil_GetDObjAnimMatAndHideParts",
#define PROF_NAME218 "R_MarkFragments_AnimatedXModel",
#define PROF_NAME219 "R_MarkFragments_AnimatedXModel_VertList",
#define PROF_NAME220 "AIThink",
#define PROF_NAME221 "AIPhysics",
#define PROF_NAME222 "AIPhysicsTrace",
#define PROF_NAME223 "AISightTrace",
#define PROF_NAME224 "AITurretSightTrace",
#define PROF_NAME225 "AIUpdateEyeInfo",
#define PROF_NAME226 "AIUpdateSight",
#define PROF_NAME227 "AIPathSearch",
#define PROF_NAME228 "AINearestNode",
#define PROF_NAME229 "AILookAhead",
#define PROF_NAME230 "G_RunFrame",
#define PROF_NAME231 "AITurretThink",
#define PROF_NAME232 "AIShoot",
#define PROF_NAME233 "SV_SightTrace",
#define PROF_NAME234 "AIGetMuzzleInfo",
#define PROF_NAME235 "Turret_Fire_Lead",
#define PROF_NAME236 "AIAnimscript",
#define PROF_NAME237 "AIAnimscriptNonBuiltIn",
#define PROF_NAME238 "G_WriteGame",
#define PROF_NAME239 "G_SaveFileAccess",
#define PROF_NAME240 "G_LoadGame",
#define PROF_NAME241 "G_LoadFileAccess",
#define PROF_NAME242 "G_FreeEntity",
#define PROF_NAME243 "G_FindConfigstringIndex",
#define PROF_NAME244 "G_ModelIndex",
#define PROF_NAME245 "G_EntAttach",
#define PROF_NAME246 "G_EntDetach",
#define PROF_NAME247 "G_DObjUpdate",
#define PROF_NAME248 "G_UpdateTagInfoOfChildren",
#define PROF_NAME249 "G_EntDetachAll",
#define PROF_NAME250 "G_EntLinkTo",
#define PROF_NAME251 "G_EntUnlink",
#define PROF_NAME252 "G_UpdateTagInfo",
#define PROF_NAME253 "FS_GetDataForFile",
#define PROF_NAME254 "SV_GetArchivedPlayerState",
#define PROF_NAME255 "SV_Frame",
#define PROF_NAME256 "SV_RunFrame",
#define PROF_NAME257 "SV_SendClientMessages",
#define PROF_NAME258 "SV_ArchiveSnapshot",
#define PROF_NAME259 "G_UpdateDvars",
#define PROF_NAME260 "G_RunFrameForEntity",
#define PROF_NAME261 "G_RunThink",
#define PROF_NAME262 "G_RunMover",
#define PROF_NAME263 "G_UpdateObjectiveToClients",
#define PROF_NAME264 "G_UpdateHudElemsToClients",
#define PROF_NAME265 "ClientEndFrame",
#define PROF_NAME266 "ClientEvents",
#define PROF_NAME267 "ClientImpacts",
#define PROF_NAME268 "IntermissionThink",
#define PROF_NAME269 "SpectatorThink",
#define PROF_NAME270 "G_UpdateClientInfo",
#define PROF_NAME271 "G_TriggerChecks",
#define PROF_NAME272 "G_TriggerCheckScripts",
#define PROF_NAME273 "IntermissionClientEndFrame",
#define PROF_NAME274 "SpectatorClientEndFrame",
#define PROF_NAME275 "ClientSpawn",
#define PROF_NAME276 "Player_UpdateCursorHints",
#define PROF_NAME277 "G_PlayerStateToEntityStateExtrapolate",
#define PROF_NAME278 "BG_PlayerStateToEntityState",
#define PROF_NAME279 "G_GetNonPVSPlayerInfo",
#define PROF_NAME280 "BG_PlayerAnimation",
#define PROF_NAME281 "BG_UpdatePlayerDObj",
#define PROF_NAME282 "SV_UserMove",
#define PROF_NAME283 "PmoveSingle",
#define PROF_NAME284 "PM_Move",
#define PROF_NAME285 "PM_Weapon",
#define PROF_NAME286 "PM_GroundTrace",
#define PROF_NAME287 "PM_Footsteps",
#define PROF_NAME288 "PM_FoliageSounds",
#define PROF_NAME289 "Mantle_Check",
#define PROF_NAME290 "SV_BuildClientSnapshot",
#define PROF_NAME291 "SV_PacketDataIsType",
#define PROF_NAME292 "WriteDeltaPlayerstate",
#define PROF_NAME293 "EmitPacketEntities",
#define PROF_NAME294 "EmitPacketClients",
#define PROF_NAME295 "SV_SendMessageToClient",
#define PROF_NAME296 "SV_TrackFieldChange",
#define PROF_NAME297 "SV_TrackPacketData",
#define PROF_NAME298 "WriteEntity",
#define PROF_NAME299 "SendPacket",
#define PROF_NAME300 "dwSendTo",
#define PROF_NAME301 "dwRecvFrom",
#define PROF_NAME302 "SV_SendClientSnapshot",
#define PROF_NAME303 "SV_UpdateBots",
#define PROF_NAME304 "SV_CalcPings",
#define PROF_NAME305 "SV_CheckTimeouts",
#define PROF_NAME306 "FakeLag_Frame",
#define PROF_NAME307 "xdelta",
#define PROF_NAME308 "xtiming",
#define PROF_NAME309 "xanim",
#define PROF_NAME310 "xskel",
#define PROF_NAME311 "xtrace",
#define PROF_NAME312 "staticModelTrace",
#define PROF_NAME313 "G_CalcTagParentAxis",
#define PROF_NAME314 "G_DObjGetLocalTagMatrix",
#define PROF_NAME315 "CG_DObjGetLocalTagMatrix",
#define PROF_NAME316 "CM_PointTraceToEntities",
#define PROF_NAME317 "CM_ClipMoveToEntities",
#define PROF_NAME318 "R_DObjCalcPose",
#define PROF_NAME319 "FX_GetBoneOrientation",
#define PROF_NAME320 "G_XAnimUpdate",
#define PROF_NAME321 "CG_AddPacketEntities",
#define PROF_NAME322 "CG_PredictPlayerState",
#define PROF_NAME323 "CG_DoControllers",
#define PROF_NAME324 "XAnimSetModel",
#define PROF_NAME325 "DObjCreateDuplicateParts",
#define PROF_NAME326 "DObjCreate",
#define PROF_NAME327 "DObjFree",
#define PROF_NAME328 "XAnimSetGoalWeight",
#define PROF_NAME329 "DObjGetHierarchyBits",
#define PROF_NAME330 "DObjCompleteHierarchyBits",
#define PROF_NAME331 "code_notify",
#define PROF_NAME332 "threads",
#define PROF_NAME333 "scriptVariable",
#define PROF_NAME334 "scriptString",
#define PROF_NAME335 "scriptMemory",
#define PROF_NAME336 "SND_init_sample",
#define PROF_NAME337 "SND_set_3d_sample_info",
#define PROF_NAME338 "SND_open_stream",
#define PROF_NAME339 "SND_Update",
#define PROF_NAME340 "SND_UpdateStream",
#define PROF_NAME341 "SND_spatialization",
#define PROF_NAME342 "SND_x3daudiocalculate",
#define PROF_NAME343 "SoundThread",
#define PROF_NAME344 "SND_entityeq",
#define PROF_NAME345 "DebugOverlays",
#define PROF_NAME346 "CG_Draw2D",
#define PROF_NAME347 "Actor_Grenade_GetTossPositionsFromHints",
#define PROF_NAME348 "Actor_Grenade_CheckGrenadeHintToss",
#define PROF_NAME349 "Actor_Grenade_CheckDesperateToss",
#define PROF_NAME350 "G_TouchTriggers",
#define PROF_NAME351 "G_DoTouchTriggers",
#define PROF_NAME352 "Actor_GetPotentialNodeList",
#define PROF_NAME353 "Actor_BadPlace_FindSafeNodeOutsideBadPlace",
#define PROF_NAME354 "VEH_VerifyPosition",
#define PROF_NAME355 "SwitchToLocalClient",
#define PROF_NAME356 "InactivePlayersSwitch",
#define PROF_NAME357 "CL_VoiceFrame",
#define PROF_NAME358 "SubmitChatData",
#define PROF_NAME359 "GetChatData",
#define PROF_NAME360 "MainThread",
#define PROF_NAME361 "MaxFPSSpin",
#define PROF_NAME362 "Live_Frame",
#define PROF_NAME363 "Phys_RunToTime",
#define PROF_NAME364 "Phys_Traces",
#define PROF_NAME365 "Phys_RunServerFrame",
#define PROF_NAME366 "Phys_Collide",
#define PROF_NAME367 "Phys_NearCallback",
#define PROF_NAME368 "Phys_WorldCollision",
#define PROF_NAME369 "Phys_WrldCollPt1",
#define PROF_NAME370 "Phys_WrldCollPt2",
#define PROF_NAME371 "Phys_OPCODE",
#define PROF_NAME372 "Phys_BoxTriColl",
#define PROF_NAME373 "Phys_BoxBoxColl",
#define PROF_NAME374 "Phys_BoxBrushColl",
#define PROF_NAME375 "Phys_BrushBrushColl",
#define PROF_NAME376 "Phys_BrushTriColl",
#define PROF_NAME377 "Phys_CylinderBrushColl",
#define PROF_NAME378 "Phys_CylinderTriColl",
#define PROF_NAME379 "Phys_CapsuleBrushColl",
#define PROF_NAME380 "Phys_CapsuleTriColl",
#define PROF_NAME381 "BldWndingsForBrsh",
#define PROF_NAME382 "Phys_Step",
#define PROF_NAME383 "Phys_PostStep",
#define PROF_NAME384 "Phys_ReduceContacts",
#define PROF_NAME385 "Phys_ODE_SOR_LCP",
#define PROF_NAME386 "DynEntCl_ProcessEntities",
#define PROF_NAME387 "DynEntCl_PhysRunToTime",
#define PROF_NAME388 "DynEntCl_DrawEntities",
#define PROF_NAME389 "DynEntCl_DrawModelEntity",
#define PROF_NAME390 "DynEntCl_DrawBrushEntity",
#define PROF_NAME391 "DynEntCl_PointTrace",
#define PROF_NAME392 "DynEntCl_ClipMoveTrace",
#define PROF_NAME393 "DynEntCl_AreaEntities",
#define PROF_NAME394 "DynEntCl_AddBreakableDrawSurfs",
#define PROF_NAME395 "DynEntSv_PointTrace",
#define PROF_NAME396 "DynEntSv_ClipMoveTrace",
#define PROF_NAME397 "DynEntSv_AreaEntities",
#define PROF_NAME398 "Ragdoll_GetDObjLocalBoneMatrix",
#define PROF_NAME399 "Ragdoll_UpdateRigidConstraint",
#define PROF_NAME400 "Ragdoll_Update",
#define PROF_NAME401 "ServerDemo_SaveHistory",
#define PROF_NAME402 "ServerDemo_CacheHistory",
#define PROF_NAME403 "FMOD_Release",
#define PROF_NAME404 "FMOD_Update",
#define PROF_NAME405 "FMOD_Codec",
#define PROF_NAME406 "FMOD_FileRead",
#define PROF_NAME407 "DrawDynEnt",
#define PROF_NAME408 "BspSurfaces",
#define PROF_NAME409 "BspSurfacesShadow",
#define PROF_NAME410 "SModelSurfaces",
#define PROF_NAME411 "SModelSurfacesShadow",
#define PROF_NAME412 "SModelLighting",
#define PROF_NAME413 "SceneEntSurfaces",
#define PROF_NAME414 "SortSceneEntSurfaces",
#define PROF_NAME415 "SceneEntSurfacesShadow",
#define PROF_NAME416 "R_GetLightSurfs",
#define PROF_NAME417 "FMOD_System_Lock",
#define PROF_NAME418 "WaitServer",
#define PROF_NAME419 "WaitSnapshot",
#define PROF_NAME420 "WaitReceiveMsg",
#define PROF_NAME421 "SoundCrit",
#define PROF_NAME422 "SoundOpen",
#define PROF_NAME423 "CodecOpen",
#define PROF_NAME424 "SoundMisc",
#define PROF_NAME425 "SoundReallyOpen",
#define PROF_NAME426 "SoundAlloc",
#define PROF_NAME427 "WaitBackendEvent",
#define PROF_NAME428 "PS3_SpeexDecode",
#define PROF_NAME429 "PS3_SpeexEncode",
#define PROF_NAME430 "PS3_VoiceDecoder",
#define PROF_NAME431 "PS3_VoiceMix",
#define PROF_NAME432 0


static constexpr const char *prof_enumNames[433] =
{
  "",
  "Probe1",
  "Probe2",
  "Probe3",
  "Probe4",
  "Probe5",
  "GProbe1",
  "GProbe2",
  "GProbe3",
  "GProbe4",
  "GProbe5",
  "CG_ProcessSnapshots",
  "CG_UpdateEntInfo",
  "CG_DrawActiveFrame",
  "R_RenderScene",
  "R_IssueRenderCommands",
  "CL_Frame",
  "CL_RunOncePerFrame",
  "SCR_UpdateFrame",
  "CL_BeginFrame",
  "CL_DrawFrame",
  "CL_EndFrame",
  "CG_DAF_UpdateEffects",
  "CG_DAF_AddLocalEntities",
  "CG_DAF_SmoothFrame",
  "CG_DrawActive",
  "CG_Pmove",
  "G_Pmove",
  "CbufExecute",
  "Com_ClientPacketEvent",
  "Com_ServerPacketEvent",
  "SV_BuildAndSendClientSnapshot",
  "NetworkRead",
  "NetworkWrite",
  "SCR_UpdateScreen",
  "CM_TerrainTrace",
  "CM_CurveTrace",
  "SV_Trace",
  "SV_TracePassed",
  "CM_Trace",
  "CM_SightTrace",
  "CM_AreaEntities",
  "CM_LinkEntity",
  "CM_PointSightTraceToEntities",
  "CM_ClipSightTraceToEntities",
  "CM_TraceBrush",
  "CM_TraceTerrain",
  "CM_SightBrush",
  "CM_SightTerrain",
  "CG_UnlinkEntity",
  "CG_LinkEntity",
  "CG_LocationalTrace",
  "CG_TraceCapsule",
  "CG_Trace",
  "CG_ClipMoveToEntities",
  "CG_ClipMoveToEntity",
  "CG_PointTraceToEntities",
  "CG_PointTraceToEntity",
  "AimTarget_ProcessEntity",
  "AimTarget_IsTargetValid",
  "AimTarget_IsTargetVisible",
  "AimTarget_CreateTarget",
  "AimAssist_UpdateGamePadInput",
  "AimAssist_UpdateMouseInput",
  "AimAssist_UpdateScreenTargets",
  "R_EmitDrawSurfList",
  "R_DrawSunShadowPartition",
  "R_BoundScene",
  "R_BoundAndPartitionScene",
  "R_AddEntitySurfaces",
  "R_DoesDrawSurfListInfoNeedFloatz",
  "R_AddWorldSurfacesDpvs",
  "R_AddShadowSurfacesDpvs",
  "GenerateSunShadow",
  "EmitSpotShadow",
  "EmitSunShadow",
  "R_SunShadowMaps",
  "R_DepthPrepass",
  "R_StreamUpdate",
  "R_StreamUpdateStatic",
  "R_StreamUpdateDynamicModels",
  "RB_StreamExecuteQueuedCommands",
  "R_StreamAlloc_Alloc",
  "R_StreamAlloc_RunOptimizationTask",
  "R_ConvexHull",
  "R_GetStaticLights",
  "R_PickFinalLights",
  "R_LightCacheTrace",
  "R_SortDrawSurfs",
  "R_SkinXModel",
  "RB_DrawTechnique",
  "RB_SetSampler",
  "RB_SetVertexShaderConstant",
  "RB_SetPixelShaderConstant",
  "RB_SetVertexDeclaration",
  "RB_SetVertexShader",
  "RB_SetPixelShader",
  "RB_SetParticleCloudConstants",
  "R_DrawSurfs",
  "rb_surfaceTable",
  "TessCodeMesh",
  "TessCloud",
  "TessXModSkin",
  "TessXModSkinCach",
  "TessXModSkinUncach",
  "TessXModRigid",
  "TessStaticModel",
  "TessStaticModelCached",
  "TessTriangles",
  "TessBModel",
  "TessSharedShadowCaster",
  "SkinXSurfaceWeight",
  "EndSurface",
  "EndSurface_Optimized",
  "EndSurface_Standard",
  "RB_ProcessPostEffects",
  "RB_ApplyPostEffects",
  "RB_UpdateAverageSceneBrightnessImage",
  "RB_GlowEffect",
  "RB_UploadWaterTexture",
  "RB_DrawSunQuerySprite",
  "R_SyncGpu",
  "FrequenciesAtTime",
  "AmplitudesFromFrequencies",
  "PixelsFromAmplitudes",
  "ProcessImage",
  "UploadImage",
  "GenerateMipMaps",
  "Present",
  "DrawIndexedPrimitive",
  "DrawIndexedPrimitiveUP",
  "SetVertexShaderConstant",
  "SetPixelShaderConstant",
  "WaitRenderer",
  "WaitFX",
  "WaitSpotLightFX",
  "WaitDepFX",
  "WaitRenderSwap",
  "WaitUpdateEvent",
  "WaitOtherThread",
  "RB_DrawProfileCmd",
  "RB_Draw3D",
  "R_SetupPass",
  "WaitWater",
  "R_Cinematic_UpdateFrame",
  "R_Cinematic_Advance",
  "BinkDoFrame",
  "BinkNextFrame",
  "BinkWait",
  "RB_LimitQueuedFrames",
  "SC_FindCasters",
  "SC_AddReceivers",
  "SC_DrawCaster",
  "SC_FindReceivers",
  "SC_DrawReceivers",
  "SC_SkinXModel",
  "RB_SetIndexData",
  "LockIndexBufferDiscard",
  "LockIndexBufferNoOverwrite",
  "LockSkinnedCache",
  "UnlockSkinnedCache",
  "RB_SetVertexData",
  "LockIndexBuffer",
  "LockVertexBuffer",
  "LockSModelBuffer",
  "BindTexture",
  "R_memcpy",
  "RB_memcpy",
  "RB_memcpy_it",
  "RB_memcpy_vt",
  "RB_memcpy_ib",
  "RB_memcpy_vb",
  "RendererSleep",
  "FrontEndSleep",
  "WorkerThread",
  "WaitForWorkerCmd",
  "WaitWorkerCmds",
  "ProcessWorkerCmds",
  "PixelShaderSurfs",
  "PixelShader",
  "StaticCull",
  "SceneEntCull",
  "DynModelCull",
  "DynBrushCull",
  "R_DrawStaticModelCmd",
  "R_DrawXModelCmd",
  "R_DrawTrianglesCmd",
  "SaveWriteThread",
  "R_VisitPortals",
  "ExecuteRenderCmds",
  "RB_memcpy_smc",
  "RB_memcpy_tris",
  "RB_memcpy_shadow",
  "FX_Update",
  "FX_UpdateOrigin",
  "FX_EndUpdate",
  "FX_GenerateVerts",
  "FX_GenElemVerts",
  "FX_EvalVisState",
  "FX_Sort",
  "FX_Draw",
  "FX_DrawElems",
  "FX_DrawSortedElems",
  "FX_Trace",
  "FX_CreateImpactMark",
  "FX_ImpactMark_World",
  "FX_ImpactMark_Models",
  "FX_ImpactMark_Generate_AddEntityModels",
  "FX_FreeLruMark",
  "FX_GenMarkVertsStaticModel",
  "FX_GenMarkVertsEnt",
  "FX_GenMarkVertsWorld",
  "FX_GetVisibility",
  "FX_StopEffect",
  "SV_FX_GetVisibility",
  "R_BoxStaticModels",
  "R_MarkFragments_SceneDObjs",
  "R_MarkUtil_GetDObjAnimMatAndHideParts",
  "R_MarkFragments_AnimatedXModel",
  "R_MarkFragments_AnimatedXModel_VertList",
  "AIThink",
  "AIPhysics",
  "AIPhysicsTrace",
  "AISightTrace",
  "AITurretSightTrace",
  "AIUpdateEyeInfo",
  "AIUpdateSight",
  "AIPathSearch",
  "AINearestNode",
  "AILookAhead",
  "G_RunFrame",
  "AITurretThink",
  "AIShoot",
  "SV_SightTrace",
  "AIGetMuzzleInfo",
  "Turret_Fire_Lead",
  "AIAnimscript",
  "AIAnimscriptNonBuiltIn",
  "G_WriteGame",
  "G_SaveFileAccess",
  "G_LoadGame",
  "G_LoadFileAccess",
  "G_FreeEntity",
  "G_FindConfigstringIndex",
  "G_ModelIndex",
  "G_EntAttach",
  "G_EntDetach",
  "G_DObjUpdate",
  "G_UpdateTagInfoOfChildren",
  "G_EntDetachAll",
  "G_EntLinkTo",
  "G_EntUnlink",
  "G_UpdateTagInfo",
  "FS_GetDataForFile",
  "SV_GetArchivedPlayerState",
  "SV_Frame",
  "SV_RunFrame",
  "SV_SendClientMessages",
  "SV_ArchiveSnapshot",
  "G_UpdateDvars",
  "G_RunFrameForEntity",
  "G_RunThink",
  "G_RunMover",
  "G_UpdateObjectiveToClients",
  "G_UpdateHudElemsToClients",
  "ClientEndFrame",
  "ClientEvents",
  "ClientImpacts",
  "IntermissionThink",
  "SpectatorThink",
  "G_UpdateClientInfo",
  "G_TriggerChecks",
  "G_TriggerCheckScripts",
  "IntermissionClientEndFrame",
  "SpectatorClientEndFrame",
  "ClientSpawn",
  "Player_UpdateCursorHints",
  "G_PlayerStateToEntityStateExtrapolate",
  "BG_PlayerStateToEntityState",
  "G_GetNonPVSPlayerInfo",
  "BG_PlayerAnimation",
  "BG_UpdatePlayerDObj",
  "SV_UserMove",
  "PmoveSingle",
  "PM_Move",
  "PM_Weapon",
  "PM_GroundTrace",
  "PM_Footsteps",
  "PM_FoliageSounds",
  "Mantle_Check",
  "SV_BuildClientSnapshot",
  "SV_PacketDataIsType",
  "WriteDeltaPlayerstate",
  "EmitPacketEntities",
  "EmitPacketClients",
  "SV_SendMessageToClient",
  "SV_TrackFieldChange",
  "SV_TrackPacketData",
  "WriteEntity",
  "SendPacket",
  "dwSendTo",
  "dwRecvFrom",
  "SV_SendClientSnapshot",
  "SV_UpdateBots",
  "SV_CalcPings",
  "SV_CheckTimeouts",
  "FakeLag_Frame",
  "xdelta",
  "xtiming",
  "xanim",
  "xskel",
  "xtrace",
  "staticModelTrace",
  "G_CalcTagParentAxis",
  "G_DObjGetLocalTagMatrix",
  "CG_DObjGetLocalTagMatrix",
  "CM_PointTraceToEntities",
  "CM_ClipMoveToEntities",
  "R_DObjCalcPose",
  "FX_GetBoneOrientation",
  "G_XAnimUpdate",
  "CG_AddPacketEntities",
  "CG_PredictPlayerState",
  "CG_DoControllers",
  "XAnimSetModel",
  "DObjCreateDuplicateParts",
  "DObjCreate",
  "DObjFree",
  "XAnimSetGoalWeight",
  "DObjGetHierarchyBits",
  "DObjCompleteHierarchyBits",
  "code_notify",
  "threads",
  "scriptVariable",
  "scriptString",
  "scriptMemory",
  "SND_init_sample",
  "SND_set_3d_sample_info",
  "SND_open_stream",
  "SND_Update",
  "SND_UpdateStream",
  "SND_spatialization",
  "SND_x3daudiocalculate",
  "SoundThread",
  "SND_entityeq",
  "DebugOverlays",
  "CG_Draw2D",
  "Actor_Grenade_GetTossPositionsFromHints",
  "Actor_Grenade_CheckGrenadeHintToss",
  "Actor_Grenade_CheckDesperateToss",
  "G_TouchTriggers",
  "G_DoTouchTriggers",
  "Actor_GetPotentialNodeList",
  "Actor_BadPlace_FindSafeNodeOutsideBadPlace",
  "VEH_VerifyPosition",
  "SwitchToLocalClient",
  "InactivePlayersSwitch",
  "CL_VoiceFrame",
  "SubmitChatData",
  "GetChatData",
  "MainThread",
  "MaxFPSSpin",
  "Live_Frame",
  "Phys_RunToTime",
  "Phys_Traces",
  "Phys_RunServerFrame",
  "Phys_Collide",
  "Phys_NearCallback",
  "Phys_WorldCollision",
  "Phys_WrldCollPt1",
  "Phys_WrldCollPt2",
  "Phys_OPCODE",
  "Phys_BoxTriColl",
  "Phys_BoxBoxColl",
  "Phys_BoxBrushColl",
  "Phys_BrushBrushColl",
  "Phys_BrushTriColl",
  "Phys_CylinderBrushColl",
  "Phys_CylinderTriColl",
  "Phys_CapsuleBrushColl",
  "Phys_CapsuleTriColl",
  "BldWndingsForBrsh",
  "Phys_Step",
  "Phys_PostStep",
  "Phys_ReduceContacts",
  "Phys_ODE_SOR_LCP",
  "DynEntCl_ProcessEntities",
  "DynEntCl_PhysRunToTime",
  "DynEntCl_DrawEntities",
  "DynEntCl_DrawModelEntity",
  "DynEntCl_DrawBrushEntity",
  "DynEntCl_PointTrace",
  "DynEntCl_ClipMoveTrace",
  "DynEntCl_AreaEntities",
  "DynEntCl_AddBreakableDrawSurfs",
  "DynEntSv_PointTrace",
  "DynEntSv_ClipMoveTrace",
  "DynEntSv_AreaEntities",
  "Ragdoll_GetDObjLocalBoneMatrix",
  "Ragdoll_UpdateRigidConstraint",
  "Ragdoll_Update",
  "ServerDemo_SaveHistory",
  "ServerDemo_CacheHistory",
  "FMOD_Release",
  "FMOD_Update",
  "FMOD_Codec",
  "FMOD_FileRead",
  "DrawDynEnt",
  "BspSurfaces",
  "BspSurfacesShadow",
  "SModelSurfaces",
  "SModelSurfacesShadow",
  "SModelLighting",
  "SceneEntSurfaces",
  "SortSceneEntSurfaces",
  "SceneEntSurfacesShadow",
  "R_GetLightSurfs",
  "FMOD_System_Lock",
  "WaitServer",
  "WaitSnapshot",
  "WaitReceiveMsg",
  "SoundCrit",
  "SoundOpen",
  "CodecOpen",
  "SoundMisc",
  "SoundReallyOpen",
  "SoundAlloc",
  "WaitBackendEvent",
  "PS3_SpeexDecode",
  "PS3_SpeexEncode",
  "PS3_VoiceDecoder",
  "PS3_VoiceMix",
  0
}; // idb


struct ProfileAtom // sizeof=0x4
{                                       // ...
    uint32_t value[1];              // ...
};
struct ProfileWritable // sizeof=0x1C
{                                       // ...
    int nesting;
    uint32_t hits;
    ProfileAtom start[3];
    ProfileAtom total;
    ProfileAtom child;
};
volatile struct ProfileReadable // sizeof=0xC
{                                       // ...
    uint32_t hits;
    ProfileAtom total;                  // ...
    ProfileAtom self;                   // ...
};

struct ProfileDrawInfo // sizeof=0x8
{                                       // ...
    int probeIndex;
    int indentation;
};

struct ProfileSettings // sizeof=0x20
{
    const char *name;
    const ProfileDrawInfo *profDrawInfo;
    int infoCount;
    int defaultProbeIndex[5];
};

struct ProfileProbe // sizeof=0x5A8
{                                       // ...
    int parity;                         // ...
    int historyCount;                   // ...
    ProfileReadable history[120];       // ...
};

struct __declspec(align(8)) ProfileReadableGlobal // sizeof=0x38
{                                       // ...
    int sequence;                       // ...
    uint32_t hits;
    long double totalClks;
    long double selfClks;
    ProfileAtom maxSelf;                // ...
    uint32_t maxHits;
    ProfileAtom min;
    ProfileAtom max;                    // ...
    ProfileReadable read;               // ...
    // padding byte
    // padding byte
    // padding byte
    // padding byte
};
struct profile_t // sizeof=0x28
{                                       // ...
    ProfileWritable write;
    volatile ProfileReadable read;
};
struct profile_guard_t // sizeof=0x8
{                                       // ...
    int id;
    profile_t **ppStack;
};

struct ProfileStack // sizeof=0x144BC
{                                       // ...
    profile_t prof_root;
    profile_t *prof_pStack[16384];
    profile_t **prof_ppStack;
    profile_t prof_array[432];
    ProfileAtom prof_overhead_internal;
    ProfileAtom prof_overhead_external;
    profile_guard_t prof_guardstack[32];
    int prof_guardpos;
    float prof_timescale;
};

struct ProfileScriptWritable // sizeof=0xC
{                                       // ...
    int refCount;
    uint32_t startTime;
    uint32_t totalTime;             // ...
};
struct ProfileScript // sizeof=0x80C
{                                       // ...
    ProfileScriptWritable write[40];    // ...
    volatile uint32_t totalTime[40]; // ...
    volatile uint32_t avgTime[40];  // ...
    volatile uint32_t maxTime[40];  // ...
    volatile float cumulative[40];      // ...
    char profileScriptNames[40][20];    // ...
    int scriptSrcBufferIndex[32];
    uint32_t srcTotal;
    uint32_t srcAvgTime;
    uint32_t srcMaxTime;
};

static const ProfileDrawInfo s_profileMain[18] =
{
  { 255, 0 },
  { 230, 0 },
  { 27, 1 },
  { 332, 1 },
  { 320, 1 },
  { 260, 1 },
  { 261, 2 },
  { 11, 1 },
  { 12, 1 },
  { 34, 0 },
  { 13, 1 },
  { 26, 2 },
  { 14, 2 },
  { 71, 3 },
  { 66, 3 },
  { 15, 1 },
  { 339, 0 },
  { 340, 0 }
}; // idb
static const ProfileDrawInfo s_profileGenericCGame[12] =
{
  { 34, 0 },
  { 129, 1 },
  { 130, 1 },
  { 128, 1 },
  { 161, 1 },
  { 71, 1 },
  { 0, 0 },
  { 230, 0 },
  { 0, 0 },
  { 346, 0 },
  { 345, 0 },
  { 322, 0 }
}; // idb
static const ProfileDrawInfo s_profileGenericGame[16] =
{
  { 238, 1 },
  { 239, 2 },
  { 240, 1 },
  { 241, 2 },
  { 242, 0 },
  { 243, 0 },
  { 244, 0 },
  { 245, 0 },
  { 246, 0 },
  { 247, 0 },
  { 248, 0 },
  { 249, 0 },
  { 250, 0 },
  { 251, 0 },
  { 252, 0 },
  { 253, 0 }
}; // idb
static const ProfileDrawInfo s_profileProbes[12] =
{
  { 1, 0 },
  { 2, 0 },
  { 3, 0 },
  { 4, 0 },
  { 5, 0 },
  { 0, 0 },
  { 6, 0 },
  { 7, 0 },
  { 8, 0 },
  { 9, 0 },
  { 10, 0 },
  { 0, 0 }
}; // idb
static const ProfileDrawInfo s_profileFrontEnd[9] =
{
  { 34, 0 },
  { 71, 1 },
  { 188, 2 },
  { 85, 1 },
  { 86, 1 },
  { 87, 2 },
  { 88, 1 },
  { 89, 2 },
  { 70, 0 }
}; // idb
static const ProfileDrawInfo s_profileRenderer[16] =
{
  { 34, 0 },
  { 129, 0 },
  { 130, 0 },
  { 98, 0 },
  { 111, 0 },
  { 100, 0 },
  { 101, 0 },
  { 103, 0 },
  { 104, 0 },
  { 105, 0 },
  { 107, 0 },
  { 108, 0 },
  { 110, 0 },
  { 112, 0 },
  { 113, 1 },
  { 114, 1 }
}; // idb
static const ProfileDrawInfo s_profileRenderer2[9] =
{
  { 166, 0 },
  { 168, 1 },
  { 169, 1 },
  { 171, 1 },
  { 190, 1 },
  { 191, 1 },
  { 192, 1 },
  { 90, 0 },
  { 189, 0 }
}; // idb
static const ProfileDrawInfo s_profileRenderer3[22] =
{
  { 128, 0 },
  { 156, 0 },
  { 157, 1 },
  { 158, 1 },
  { 160, 0 },
  { 161, 0 },
  { 163, 1 },
  { 164, 0 },
  { 118, 1 },
  { 116, 0 },
  { 115, 1 },
  { 117, 2 },
  { 120, 0 },
  { 121, 0 },
  { 82, 0 },
  { 78, 0 },
  { 79, 1 },
  { 80, 1 },
  { 83, 1 },
  { 81, 0 },
  { 65, 0 },
  { 144, 0 }
}; // idb
static const ProfileDrawInfo s_profileCinematics[5] = { { 144, 0 }, { 145, 0 }, { 146, 1 }, { 147, 1 }, { 148, 1 } }; // idb
static const ProfileDrawInfo s_profileWater[7] =
{
  { 119, 0 },
  { 122, 1 },
  { 123, 1 },
  { 124, 1 },
  { 125, 1 },
  { 126, 1 },
  { 127, 1 }
}; // idb
static const ProfileDrawInfo s_profileSnd[4] = { { 336, 0 }, { 337, 0 }, { 338, 0 }, { 344, 0 } }; // idb
static const ProfileDrawInfo s_profileXanim[12] =
{
  { 313, 0 },
  { 314, 0 },
  { 315, 0 },
  { 318, 0 },
  { 319, 0 },
  { 320, 0 },
  { 321, 0 },
  { 307, 0 },
  { 308, 0 },
  { 309, 0 },
  { 310, 0 },
  { 311, 0 }
}; // idb
static const ProfileDrawInfo s_profileXanim2[8] =
{
  { 324, 0 },
  { 325, 0 },
  { 326, 0 },
  { 327, 0 },
  { 328, 0 },
  { 329, 0 },
  { 330, 0 },
  { 323, 0 }
}; // idb
static const ProfileDrawInfo s_profileScript[4] = { { 331, 0 }, { 332, 0 }, { 334, 0 }, { 335, 0 } }; // idb
static const ProfileDrawInfo s_profileFx[30] =
{
  { 193, 0 },
  { 194, 1 },
  { 203, 2 },
  { 204, 1 },
  { 205, 2 },
  { 206, 2 },
  { 207, 3 },
  { 215, 3 },
  { 216, 3 },
  { 217, 4 },
  { 218, 4 },
  { 219, 5 },
  { 208, 2 },
  { 195, 0 },
  { 209, 0 },
  { 210, 0 },
  { 211, 0 },
  { 196, 0 },
  { 197, 1 },
  { 198, 2 },
  { 199, 1 },
  { 200, 0 },
  { 201, 1 },
  { 202, 2 },
  { 212, 0 },
  { 213, 0 },
  { 97, 0 },
  { 134, 0 },
  { 136, 0 },
  { 135, 0 }
}; // idb
static const ProfileDrawInfo s_profilePrediction[2] = { { 34, 0 }, { 322, 1 } }; // idb
static const ProfileDrawInfo s_profileTrace[18] =
{
  { 37, 0 },
  { 38, 0 },
  { 39, 0 },
  { 40, 0 },
  { 35, 0 },
  { 36, 0 },
  { 41, 0 },
  { 316, 0 },
  { 312, 0 },
  { 42, 0 },
  { 43, 0 },
  { 44, 0 },
  { 45, 0 },
  { 46, 0 },
  { 47, 0 },
  { 48, 0 },
  { 317, 0 },
  { 233, 0 }
}; // idb
static const ProfileDrawInfo s_profileServer[37] =
{
  { 254, 0 },
  { 255, 0 },
  { 257, 0 },
  { 302, 1 },
  { 290, 2 },
  { 292, 2 },
  { 293, 2 },
  { 298, 3 },
  { 296, 4 },
  { 294, 2 },
  { 295, 2 },
  { 296, 3 },
  { 297, 3 },
  { 299, 2 },
  { 300, 3 },
  { 301, 0 },
  { 258, 0 },
  { 230, 0 },
  { 259, 1 },
  { 320, 1 },
  { 260, 1 },
  { 263, 1 },
  { 264, 1 },
  { 265, 1 },
  { 214, 3 },
  { 276, 2 },
  { 279, 2 },
  { 272, 2 },
  { 266, 1 },
  { 267, 1 },
  { 303, 0 },
  { 282, 0 },
  { 27, 0 },
  { 283, 1 },
  { 289, 2 },
  { 284, 2 },
  { 286, 2 }
}; // idb
static const ProfileDrawInfo s_profileTrigger[1] = { { 350, 0 } }; // idb

static const ProfileDrawInfo s_profileUpdateScreen[13] =
{
                {0x22, 0}    ,
                {0x12, 1}    ,
                {0x13, 2}    ,
                {0x14, 2}    ,
                {0x0D, 3}    ,
                {0x16, 4}    ,
                {0x17, 4}    ,
                {0x18, 4}    ,
                {0x15A, 4}   ,
                {0x19, 4}    ,
                {0x0E, 5}    ,
                {0x15, 2}    ,
                { 0x0F, 3 }  ,
};
static const ProfileDrawInfo s_profileThread[6] =
{
    {0x168, 0},
    {0xBD, 0},
    {0x9F, 0},
    {0x86, 0},
    {0x88, 0},
    {0x87, 0}
};

static const ProfileDrawInfo s_profilePhys[22] =
{
    { 0x16B, 0},
    { 0x16C, 1},
    { 0x16D, 1},
    { 0x16E, 2},
    { 0x16F, 3},
    { 0x173, 4},
    { 0x170, 4},
    { 0x171, 5},
    { 0x172, 5},
    { 0x174, 6},
    { 0x176, 6},
    { 0x177, 6},
    { 0x178, 6},
    { 0x179, 6},
    { 0x17A, 6},
    { 0x17B, 6},
    { 0x17C, 6},
    { 0x17D, 7},
    { 0x175, 4},
    { 0x180, 4},
    { 0x17E, 2},
    { 0x181, 3 },
};

static const ProfileDrawInfo s_shadowCookie[6] =
{
    {0x96, 0},
    {0x97, 0},
    {0x98, 1},
    {0x9B, 2},
    {0x99, 2},
    {0x9A, 0}
};

static const ProfileDrawInfo s_profileCgTrace[9] =
{
    {0x31, 0},
    {0x32, 0},
    {0x33, 0},
    {0x34, 0},
    {0x35, 0},
    {0x36, 1},
    {0x37, 2},
    {0x38, 1},
    {0x39, 2}
};

static const ProfileDrawInfo s_profileDynEnts[11] =
{
    {0x182, 0},
    {0x183, 2},
    {0x184, 1},
    {0x185, 2},
    {0x186, 2},
    {0x187, 0},
    {0x188, 0},
    {0x189, 0},
    {0x18B, 0},
    {0x18C, 0},
    {0x18D, 0},
};

static const ProfileDrawInfo s_profileAimAssist[7] =
{
    {0x3A, 0}  ,
    {0x3B, 1}  ,
    {0x3C, 1}  ,
    {0x3D, 1}  ,
    {0x3E, 0}  ,
    {0x3F, 0}  ,
    { 0x40, 0 },
};

static const ProfileSettings s_profileArrays[29] =
{
  { "main", s_profileMain, 18, {230, 34, 339, 0, 0}},
  { "updateScreen", s_profileUpdateScreen, 13, { 0, 0, 0, 0, 0 } },
  { "thread", s_profileThread, 6, { 360, 189, 0, 0, 0 } },
  { "generic", s_profileGenericCGame, 12, { 34, 230, 0, 0, 0 } },
  { "generic2", s_profileGenericGame, 16, { 243, 245, 246, 247, 253 } },
  { "probes", s_profileProbes, 12, { 1, 6, 0, 0, 0 } },
  { "probe", s_profileProbes, 12, { 1, 2, 3, 4, 5 } },
  { "gprobe", s_profileProbes, 12, { 6, 7, 8, 9, 10 } },
  { "frontend", s_profileFrontEnd, 9, { 34, 71, 89, 87, 88 } },
  { "renderer", s_profileRenderer, 16, { 34, 98, 112, 0, 0 } },
  { "renderer2", s_profileRenderer2, 9, { 166, 169, 171, 0, 0 } },
  { "renderer3", s_profileRenderer3, 22, { 121, 0, 0, 0, 0 } },
  { "cinematics", s_profileCinematics, 5, { 144, 145, 146, 147, 0 } },
  { "phys", s_profilePhys, 22, { 0, 0, 0, 0, 0 } },
  { "shadowcookie", s_shadowCookie, 6, { 0, 0, 0, 0, 0 } },
  { "water", s_profileWater, 7, { 119, 122, 123, 124, 0 } },
  { "snd", s_profileSnd, 4, { 336, 337, 338, 0, 0 } },
  { "xanim", s_profileXanim, 12, { 314, 315, 318, 320, 321 } },
  { "xanim2", s_profileXanim2, 8, { 326, 325, 324, 0, 0 } },
  { "script", s_profileScript, 4, { 332, 334, 0, 0, 0 } },
  { "fx", s_profileFx, 30, { 0, 0, 0, 0, 0 } },
  { "prediction", s_profilePrediction, 2, { 34, 322, 0, 0, 0 } },
  { "trace", s_profileTrace, 18, { 39, 47, 45, 48, 316 } },
  { "cgtrace", s_profileCgTrace, 9, { 49, 50, 51, 52, 0 } },
  { "server", s_profileServer, 37, { 0, 0, 0, 0, 0 } },
  { "trigger", s_profileTrigger, 1, { 350, 0, 0, 0, 0 } },
  { "dynent", s_profileDynEnts, 11, { 0, 0, 0, 0, 0 } },
  { "aimassist", s_profileAimAssist, 7, { 0, 0, 0, 0, 0 } },
  { NULL, NULL, 0, { 0, 0, 0, 0, 0 } }
}; // idb

#ifdef TRACY_ENABLE
#ifndef TRACY_ON_DEMAND
#error This should be left ON
#endif

#include <tracy/Tracy.hpp>
#include <tracy/TracyC.h>

inline void __cdecl Profile_Guard(int id) {}
inline void __cdecl Profile_Unguard(int id) {}
inline void __cdecl Profile_SetTotal(int index, int total) {}
inline void Profile_ResetScriptCounters() {}
inline void __cdecl Profile_ResetCounters(int system) {}
inline void __cdecl Profile_Recover(int id) {}
inline void __cdecl Profile_InitContext(int profileContext) {}
inline ProfileStack *__cdecl Profile_GetStackForContext(int profileContext) { return NULL;  }
inline ProfileScript *__cdecl Profile_GetScript() { return NULL;  }
inline int __cdecl Profile_GetEnumParity(uint32_t profEnum) { return 0; }
inline int __cdecl Profile_GetDisplayThread() { return 0; }
inline void __cdecl Profile_EndScripts(uint32_t profileFlags) {} 
inline void __cdecl Profile_EndScript(int profileIndex) {}
inline void __cdecl Profile_BeginScripts(uint32_t profileFlags) {}
inline void __cdecl Profile_BeginScript(int profileIndex) {}
inline int __cdecl Profile_AddScriptName(char *profileName) { return 0; }
inline void __cdecl Profile_ResetCountersForContext(int profileContext, int system) {}
inline const char *__cdecl Profile_MissingEnd() { return ""; }

void Profile_Init();

void Profile_Begin(int nameIndex);
void Profile_EndInternal(double *duration);

#define PROF_SCOPED(name) ZoneScopedN(name)
#define PROFLOAD_SCOPED(name) PROF_SCOPED(name)

#else
void Profile_Init();
void __cdecl Profile_Guard(int id);
void __cdecl Profile_Unguard(int id);
void __cdecl Profile_SetTotal(int index, int total);
void Profile_ResetScriptCounters();
void __cdecl Profile_ResetCounters(int system);
void __cdecl Profile_Recover(int id);
void __cdecl Profile_InitContext(int profileContext);
void __cdecl Profile_InitContext(int profileContext);
ProfileStack *__cdecl Profile_GetStackForContext(int profileContext);
ProfileScript *__cdecl Profile_GetScript();
int __cdecl Profile_GetEnumParity(uint32_t profEnum);
int __cdecl Profile_GetDisplayThread();
void __cdecl Profile_EndScripts(uint32_t profileFlags);
void __cdecl Profile_EndScript(int profileIndex);
void __cdecl Profile_BeginScripts(uint32_t profileFlags);
void __cdecl Profile_BeginScript(int profileIndex);
int __cdecl Profile_AddScriptName(char *profileName);
void __cdecl Profile_ResetCountersForContext(int profileContext, int system);
const char *__cdecl Profile_MissingEnd();

void __cdecl Profile_Begin(int index);
int __cdecl Profile_EndInternal(long double *duration);

#define PROF_SCOPED(name) // Disable Profiling without Tracy
#define PROFLOAD_SCOPED(name) PROF_SCOPED(name)
#define ZoneText(str, len)
#define ZoneTextF(fmt, ...)

// LWSS: The profiler blocks were changed from the decomp to be Scoped blocks. This seems to be more accurate as well.
// The old profiler isn't implemented now. You could re-implement it with some sort of RAII wrapper if you really wanted.

#endif


extern const dvar_t *profile;
extern const dvar_t *profile_thread;
extern const dvar_t *profile_rowcount;

extern ProfileScript profileScript;